// Code generated by hotswap. DO NOT EDIT.

package plugin

import (
	"github.com/sandwich-go/hotswap"
	dog "github.com/sandwich-go/hotswap/demo/slink/plugin/dog"
)

func init() {
	HotswapStaticPlugins["dog"] = &hotswap.StaticPlugin{
		Name: "dog",
		PluginFuncs: hotswap.NewPluginFuncs(
			dog.Export,
			dog.HotswapLiveFuncs,
			dog.HotswapLiveTypes,
			dog.Import,
			dog.InvokeFunc,
			dog.OnFree,
			dog.OnInit,
			dog.OnLoad,
			dog.Reloadable,
		),
	}
}
